import { MigrationInterface, QueryRunner } from "typeorm";

export class Versionentity1780921662391 implements MigrationInterface {
    name = 'Versionentity1780921662391'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_692a909ee0fa9383e7859f9b406"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a149c790c0e3be716ec3403172"`);
        await queryRunner.query(`CREATE TABLE "vehicle_types" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "updatedBy" character varying, "createdBy" character varying, "name" character varying NOT NULL, CONSTRAINT "PK_73d1e40f4add7f4f6947acad3a8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "system_settings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "updatedBy" character varying, "createdBy" character varying, "key" character varying NOT NULL, "value" jsonb, "description" text, CONSTRAINT "UQ_b1b5bc664526d375c94ce9ad43d" UNIQUE ("key"), CONSTRAINT "PK_82521f08790d248b2a80cc85d40" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "system_records" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "updatedBy" character varying, "createdBy" character varying, "driverId" uuid, "bookingId" uuid, "platformEarning" numeric(10,2) NOT NULL DEFAULT '0', "driverEarned" numeric(10,2) NOT NULL DEFAULT '0', "discountApplied" numeric(10,2) NOT NULL DEFAULT '0', "amountMade" numeric(10,2) NOT NULL DEFAULT '0', "isCancelled" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_61fc6428aedb9fb4127b20ccc40" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "app_version_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "updatedBy" character varying, "createdBy" character varying, "app_type" character varying NOT NULL, "platform" character varying NOT NULL, "min_version" character varying NOT NULL, "latest_version" character varying NOT NULL, "is_force_update" boolean NOT NULL DEFAULT false, "update_message" text, CONSTRAINT "PK_3cd9e4fdbe0071e1a72ed6bec47" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "agent_referrals" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "updatedBy" character varying, "createdBy" character varying, "agentId" uuid NOT NULL, "driverId" uuid NOT NULL, "referralCode" character varying, "referredAt" TIMESTAMP WITH TIME ZONE, "earnedAmount" numeric(10,2) NOT NULL DEFAULT '0', CONSTRAINT "PK_f03e7602e629bc7d134528161b8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e432486bf11490dee617c060de" ON "agent_referrals" ("agentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c8bec3851cfe4add5ff490d7bd" ON "agent_referrals" ("driverId") `);
        await queryRunner.query(`ALTER TABLE "agents" DROP COLUMN "walletBalance"`);
        await queryRunner.query(`ALTER TABLE "agents" DROP COLUMN "bankAccountName"`);
        await queryRunner.query(`ALTER TABLE "agents" DROP COLUMN "bankAccountNumber"`);
        await queryRunner.query(`ALTER TABLE "agents" DROP COLUMN "bankCode"`);
        await queryRunner.query(`ALTER TABLE "beneficiaries" DROP COLUMN "bankAccountName"`);
        await queryRunner.query(`ALTER TABLE "beneficiaries" DROP COLUMN "bankAccountNumber"`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP COLUMN "bvnVerified"`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP COLUMN "bvnData"`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP COLUMN "bvnVerifiedAt"`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP COLUMN "ninVerified"`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP COLUMN "ninData"`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP COLUMN "ninVerifiedAt"`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP COLUMN "licenseExpiry"`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP COLUMN "walletBalance"`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP COLUMN "kycStatus"`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP COLUMN "bvn"`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP COLUMN "nin"`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP COLUMN "licenseNumber"`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP COLUMN "bankAccountName"`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP COLUMN "bankAccountNumber"`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP COLUMN "bankCode"`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP COLUMN "bankName"`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP COLUMN "transactionPin"`);
        await queryRunner.query(`ALTER TABLE "trips" DROP COLUMN "origin"`);
        await queryRunner.query(`ALTER TABLE "trips" DROP COLUMN "destination"`);
        await queryRunner.query(`ALTER TABLE "payouts" DROP COLUMN "processedAt"`);
        await queryRunner.query(`ALTER TABLE "payouts" DROP COLUMN "declineReason"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "city" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "country" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "address" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "gender" character varying`);
        await queryRunner.query(`ALTER TABLE "agents" ADD "address" character varying`);
        await queryRunner.query(`ALTER TABLE "agents" ADD "city" character varying`);
        await queryRunner.query(`ALTER TABLE "agents" ADD "terms" character varying`);
        await queryRunner.query(`ALTER TABLE "agents" ADD "stateOfResidence" character varying`);
        await queryRunner.query(`ALTER TABLE "agents" ADD "status" character varying NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE "agents" ADD "currentBalance" numeric(10,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "beneficiaries" ADD "driverId" uuid`);
        await queryRunner.query(`ALTER TABLE "beneficiaries" ADD "recipientCode" character varying`);
        await queryRunner.query(`ALTER TABLE "beneficiaries" ADD "agentId" uuid`);
        await queryRunner.query(`ALTER TABLE "beneficiaries" ADD "ownerType" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "beneficiaries" ADD "bankHolderName" character varying`);
        await queryRunner.query(`ALTER TABLE "beneficiaries" ADD "accountNumber" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "beneficiaries" ADD "recipientCodeId" uuid`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD "kycComplete" character varying NOT NULL DEFAULT 'not_started'`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD "vehicleId" uuid`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD "license" character varying`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD "reason" character varying`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD "yearOfExpire" date`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD "currentBalance" numeric(10,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD "vehicleVerified" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD "vehicleVerifiedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD "pin" character varying`);
        await queryRunner.query(`ALTER TABLE "payouts" ADD "agentId" uuid`);
        await queryRunner.query(`ALTER TABLE "payouts" ADD "beneficiaryId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payouts" ADD "paymentMethod" character varying`);
        await queryRunner.query(`ALTER TABLE "payouts" ADD "payoutableType" character varying`);
        await queryRunner.query(`ALTER TABLE "payouts" ADD "payoutableId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payouts" ADD "narration" character varying`);
        await queryRunner.query(`ALTER TABLE "payouts" ADD "transactionDate" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "payouts" ADD "paymentDetails" jsonb`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "adminId" uuid`);
        await queryRunner.query(`ALTER TABLE "payouts" DROP CONSTRAINT "FK_432bd34c495ea23e5c182eb0e42"`);
        await queryRunner.query(`ALTER TABLE "payouts" ALTER COLUMN "driverId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "userId" DROP NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_1905b0a6526f1bd162a4556563" ON "beneficiaries" ("driverId", "agentId") `);
        await queryRunner.query(`ALTER TABLE "beneficiaries" ADD CONSTRAINT "FK_1770e517703c1619654083b47e4" FOREIGN KEY ("recipientCodeId") REFERENCES "drivers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "beneficiaries" ADD CONSTRAINT "FK_3b5743682bff9e6a4d0e9cef237" FOREIGN KEY ("agentId") REFERENCES "agents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD CONSTRAINT "FK_147d9e5f169aa23722c8d337d51" FOREIGN KEY ("vehicleId") REFERENCES "vehicles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "system_records" ADD CONSTRAINT "FK_bacec984adc93211c682976dafb" FOREIGN KEY ("driverId") REFERENCES "drivers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "system_records" ADD CONSTRAINT "FK_c5816ec0163834c9c04c0c7c250" FOREIGN KEY ("bookingId") REFERENCES "bookings"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payouts" ADD CONSTRAINT "FK_432bd34c495ea23e5c182eb0e42" FOREIGN KEY ("driverId") REFERENCES "drivers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payouts" ADD CONSTRAINT "FK_ad25e70ca1fd1c86e2ad5edcbbf" FOREIGN KEY ("agentId") REFERENCES "agents"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payouts" ADD CONSTRAINT "FK_672112e73dccff279d1cbe47ab5" FOREIGN KEY ("beneficiaryId") REFERENCES "beneficiaries"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_692a909ee0fa9383e7859f9b406" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_4509d5b418f7eb05ac668d50564" FOREIGN KEY ("adminId") REFERENCES "admins"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agent_referrals" ADD CONSTRAINT "FK_e432486bf11490dee617c060de5" FOREIGN KEY ("agentId") REFERENCES "agents"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agent_referrals" ADD CONSTRAINT "FK_c8bec3851cfe4add5ff490d7bd0" FOREIGN KEY ("driverId") REFERENCES "drivers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "agent_referrals" DROP CONSTRAINT "FK_c8bec3851cfe4add5ff490d7bd0"`);
        await queryRunner.query(`ALTER TABLE "agent_referrals" DROP CONSTRAINT "FK_e432486bf11490dee617c060de5"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_4509d5b418f7eb05ac668d50564"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_692a909ee0fa9383e7859f9b406"`);
        await queryRunner.query(`ALTER TABLE "payouts" DROP CONSTRAINT "FK_672112e73dccff279d1cbe47ab5"`);
        await queryRunner.query(`ALTER TABLE "payouts" DROP CONSTRAINT "FK_ad25e70ca1fd1c86e2ad5edcbbf"`);
        await queryRunner.query(`ALTER TABLE "payouts" DROP CONSTRAINT "FK_432bd34c495ea23e5c182eb0e42"`);
        await queryRunner.query(`ALTER TABLE "system_records" DROP CONSTRAINT "FK_c5816ec0163834c9c04c0c7c250"`);
        await queryRunner.query(`ALTER TABLE "system_records" DROP CONSTRAINT "FK_bacec984adc93211c682976dafb"`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP CONSTRAINT "FK_147d9e5f169aa23722c8d337d51"`);
        await queryRunner.query(`ALTER TABLE "beneficiaries" DROP CONSTRAINT "FK_3b5743682bff9e6a4d0e9cef237"`);
        await queryRunner.query(`ALTER TABLE "beneficiaries" DROP CONSTRAINT "FK_1770e517703c1619654083b47e4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1905b0a6526f1bd162a4556563"`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "userId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payouts" ALTER COLUMN "driverId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payouts" ADD CONSTRAINT "FK_432bd34c495ea23e5c182eb0e42" FOREIGN KEY ("driverId") REFERENCES "drivers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "adminId"`);
        await queryRunner.query(`ALTER TABLE "payouts" DROP COLUMN "paymentDetails"`);
        await queryRunner.query(`ALTER TABLE "payouts" DROP COLUMN "transactionDate"`);
        await queryRunner.query(`ALTER TABLE "payouts" DROP COLUMN "narration"`);
        await queryRunner.query(`ALTER TABLE "payouts" DROP COLUMN "payoutableId"`);
        await queryRunner.query(`ALTER TABLE "payouts" DROP COLUMN "payoutableType"`);
        await queryRunner.query(`ALTER TABLE "payouts" DROP COLUMN "paymentMethod"`);
        await queryRunner.query(`ALTER TABLE "payouts" DROP COLUMN "beneficiaryId"`);
        await queryRunner.query(`ALTER TABLE "payouts" DROP COLUMN "agentId"`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP COLUMN "pin"`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP COLUMN "vehicleVerifiedAt"`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP COLUMN "vehicleVerified"`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP COLUMN "currentBalance"`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP COLUMN "yearOfExpire"`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP COLUMN "reason"`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP COLUMN "license"`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP COLUMN "vehicleId"`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP COLUMN "kycComplete"`);
        await queryRunner.query(`ALTER TABLE "beneficiaries" DROP COLUMN "recipientCodeId"`);
        await queryRunner.query(`ALTER TABLE "beneficiaries" DROP COLUMN "accountNumber"`);
        await queryRunner.query(`ALTER TABLE "beneficiaries" DROP COLUMN "bankHolderName"`);
        await queryRunner.query(`ALTER TABLE "beneficiaries" DROP COLUMN "ownerType"`);
        await queryRunner.query(`ALTER TABLE "beneficiaries" DROP COLUMN "agentId"`);
        await queryRunner.query(`ALTER TABLE "beneficiaries" DROP COLUMN "recipientCode"`);
        await queryRunner.query(`ALTER TABLE "beneficiaries" DROP COLUMN "driverId"`);
        await queryRunner.query(`ALTER TABLE "agents" DROP COLUMN "currentBalance"`);
        await queryRunner.query(`ALTER TABLE "agents" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "agents" DROP COLUMN "stateOfResidence"`);
        await queryRunner.query(`ALTER TABLE "agents" DROP COLUMN "terms"`);
        await queryRunner.query(`ALTER TABLE "agents" DROP COLUMN "city"`);
        await queryRunner.query(`ALTER TABLE "agents" DROP COLUMN "address"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "gender"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "address"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "country"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "city"`);
        await queryRunner.query(`ALTER TABLE "payouts" ADD "declineReason" character varying`);
        await queryRunner.query(`ALTER TABLE "payouts" ADD "processedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "trips" ADD "destination" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "trips" ADD "origin" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD "transactionPin" character varying`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD "bankName" character varying`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD "bankCode" character varying`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD "bankAccountNumber" character varying`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD "bankAccountName" character varying`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD "licenseNumber" character varying`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD "nin" character varying`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD "bvn" character varying`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD "kycStatus" character varying NOT NULL DEFAULT 'not_started'`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD "walletBalance" numeric(10,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD "licenseExpiry" date`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD "ninVerifiedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD "ninData" jsonb`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD "ninVerified" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD "bvnVerifiedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD "bvnData" jsonb`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD "bvnVerified" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "beneficiaries" ADD "bankAccountNumber" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "beneficiaries" ADD "bankAccountName" character varying`);
        await queryRunner.query(`ALTER TABLE "agents" ADD "bankCode" character varying`);
        await queryRunner.query(`ALTER TABLE "agents" ADD "bankAccountNumber" character varying`);
        await queryRunner.query(`ALTER TABLE "agents" ADD "bankAccountName" character varying`);
        await queryRunner.query(`ALTER TABLE "agents" ADD "walletBalance" numeric(10,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c8bec3851cfe4add5ff490d7bd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e432486bf11490dee617c060de"`);
        await queryRunner.query(`DROP TABLE "agent_referrals"`);
        await queryRunner.query(`DROP TABLE "app_version_history"`);
        await queryRunner.query(`DROP TABLE "system_records"`);
        await queryRunner.query(`DROP TABLE "system_settings"`);
        await queryRunner.query(`DROP TABLE "vehicle_types"`);
        await queryRunner.query(`CREATE INDEX "IDX_a149c790c0e3be716ec3403172" ON "beneficiaries" ("beneficiaryableId", "beneficiaryableType") `);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_692a909ee0fa9383e7859f9b406" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
